---
kubeVersion: 1.27.2
helmDefaults:
  timeout: 600
  createNamespace: false

commonLabels:
  tier: slime-test

releases:
  - name: minimal
    namespace: chatwork
    version: 1.1.0
    chart: "../../../modules/tshinow/chatwork-charts/slime"
    installedTemplate: false
    values:
      - values/minimal/cronjob.yaml.gotmpl

  - name: full
    namespace: chatwork
    version: 1.1.0
    chart: "../../../modules/tshinow/chatwork-charts/slime"
    installedTemplate: true
    values:
      - values/full/configmap.yaml.gotmpl
      - values/full/cronjob.yaml.gotmpl
      - values/full/secret.yaml.gotmpl
